from django.db import migrations

def add_questions(apps, schema_editor):
    Question = apps.get_model('mchatr', 'Question')
    questions = [
    "SEU FILHO GOSTA DE SE BALANÇAR, DE PULAR NO SEU JOELHO, ETC.?",
    "SEU FILHO TEM INTERESSE POR OUTRAS CRIANÇAS?",
    "SEU FILHO GOSTA DE SUBIR EM COISAS, COMO ESCADAS OU MÓVEIS?",
    "SEU FILHO GOSTA DE BRINCAR DE ESCONDER E MOSTRAR O ROSTO OU DE ESCONDE-ESCONDE?",
    "SEU FILHO JÁ BRINCOU DE FAZ-DE-CONTA, COMO, POR EXEMPLO, FAZER DE CONTA QUE ESTÁ FALANDO NO TELEFONE OU QUE ESTÁ CUIDANDO DE BONECA, OU QUALQUER OUTRA BRINCADEIRA DE FAZ-DE-CONTA?",
    "SEU FILHO JÁ USOU O DEDO INDICADOR DELE PARA APONTAR, PARA PEDIR ALGUMA COISA?",
    "SEU FILHO JÁ USOU O DEDO INDICADOR DELE PARA APONTAR, PARA INDICAR INTERESSE EM ALGO?",
    "SEU FILHO CONSEGUE BRINCAR DE FORMA CORRETA COM BRINQUEDOS PEQUENOS (EX. CARROS OU BLOCOS), SEM APENAS COLOCAR NA BOCA, REMEXER NO BRINQUEDO OU DEIXAR O BRINQUEDO CAIR?",
    "O SEU FILHO ALGUMA VEZ TROUXE OBJETOS PARA VOCÊ (PAIS) PARA LHE MOSTRAR ESTE OBJETO?",
    "O SEU FILHO OLHA PARA VOCÊ NO OLHO POR MAIS DE UM SEGUNDO OU DOIS?",
    "O SEU FILHO JÁ PARECEU MUITO SENSÍVEL AO BARULHO (EX. TAPANDO OS OUVIDOS)?",
    "O SEU FILHO SORRI EM RESPOSTA AO SEU ROSTO OU AO SEU SORRISO?",
    "O SEU FILHO IMITA VOCÊ? (EX. VOCÊ FAZ EXPRESSÕES/CARETAS E SEU FILHO IMITA?)",
    "O SEU FILHO RESPONDE QUANDO VOCÊ CHAMA ELE PELO NOME?",
    "SE VOCÊ APONTA UM BRINQUEDO DO OUTRO LADO DO CÔMODO, O SEU FILHO OLHA PARA ELE?",
    "SEU FILHO JÁ SABE ANDAR?",
    "O SEU FILHO OLHA PARA COISAS QUE VOCÊ ESTÁ OLHANDO?",
    "O SEU FILHO FAZ MOVIMENTOS ESTRANHOS COM OS DEDOS PERTO DO ROSTO DELE?",
    "O SEU FILHO TENTA ATRAIR A SUA ATENÇÃO PARA A ATIVIDADE DELE?",
    "VOCÊ ALGUMA VEZ JÁ SE PERGUNTOU SE SEU FILHO É SURDO?",
    "O SEU FILHO ENTENDE O QUE AS PESSOAS DIZEM?",
    "O SEU FILHO ÀS VEZES FICA AÉREO, “OLHANDO PARA O NADA” OU CAMINHANDO SEM DIREÇÃO DEFINIDA?",
    "O SEU FILHO OLHA PARA O SEU ROSTO PARA CONFERIR A SUA REAÇÃO QUANDO VÊ ALGO ESTRANHO?"
]
    for q in questions:
        Question.objects.create(text=q)

class Migration(migrations.Migration):

    dependencies = [
        ('mchatr', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_questions),
    ]
