# Generated by Django 5.0.4 on 2024-05-08 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mchatr', '0004_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('turma', models.CharField(max_length=50)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mchatr.school')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='auth.User')),
            ],
        ),
    ]
