# Generated by Django 5.0.4 on 2024-05-08 04:56

import django.db.models.deletion
from django.db import migrations, models


def create_initial_data(apps, schema_editor):
    Turma = apps.get_model('mchatr', 'Turma')

    Turma.objects.create(name='Berçário I')
    Turma.objects.create(name='Berçário II')
    Turma.objects.create(name='Mini Grupo I')
    Turma.objects.create(name='Mini Grupo II')

class Migration(migrations.Migration):

    dependencies = [
        ('mchatr', '0005_turma_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mchatr.turma'),
        ),
        migrations.RunPython(create_initial_data),
    ]
