# Generated by Django 5.0.4 on 2024-05-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mchatr', '0006_alter_student_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mchatr_score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
