# Generated by Django 5.0.4 on 2024-04-17 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField(default=0)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('Alto', 'Alto'), ('Médio', 'Médio'), ('Baixo', 'Baixo')], max_length=10)),
                ('cod_ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.questionario')),
                ('cod_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.usuario')),
            ],
        ),
    ]
