# Generated by Django 5.0.4 on 2024-04-17 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_questionario_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='escola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.escola'),
        ),
    ]
