# Generated by Django 5.0.4 on 2024-04-18 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_alter_usuario_escola'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questionario',
            new_name='Aluno',
        ),
    ]
