# Generated by Django 5.0.4 on 2024-04-18 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_rename_questionario_aluno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultado',
            old_name='cod_ques',
            new_name='cod_alu',
        ),
    ]
