# Generated by Django 5.0.4 on 2024-04-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_rename_cod_ques_resultado_cod_alu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='nivel',
        ),
        migrations.AddField(
            model_name='aluno',
            name='nivel',
            field=models.CharField(choices=[('Alto', 'Alto'), ('Médio', 'Médio'), ('Baixo', 'Baixo')], max_length=10, null=True),
        ),
    ]
